In [16]:
#Import libraries

import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import os
from pathlib import Path

In [17]:
# Define the main project folder
project_folder = Path( r"C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026")

# Define the folder containing the original datasets
raw_data_folder = project_folder / "raw_data"

# Define the folder for cleaned datasets and reports
output_folder = project_folder / "cleaned_data"

# Create the output folder if it does not already exist
output_folder.mkdir(exist_ok=True)

print("Project Folder:", project_folder)
print("Raw Data Folder:", raw_data_folder)
print("Output Folder:", output_folder)

Project Folder: C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026
Raw Data Folder: C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026\raw_data
Output Folder: C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026\cleaned_data

In [18]:
# Read the original Labs dataset
df = pd.read_csv(raw_data_folder / "patienthistory.csv")

# Keep an original copy
df_original = df.copy()

# Display the first five records
display(df.head())

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
df.head()
df.info()
df.describe()

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
0,857781,0,0,1,0,0.0,1,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0
1,743087,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0
2,866418,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0
3,775928,0,0,1,0,0.0,0,1.0,0,0,0,0,0.0,0,2.0,nontypeii,0
4,810128,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0

Rows: 2008
Columns: 17
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2008 entries, 0 to 2007
Data columns (total 17 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   inpatient_number                           2008 non-null   int64
 1   cerebrovascular_disease                    2008 non-null   int64
 2   dementia                                   2008 non-null   int64
 3   chronic_obstructive_pulmonary_disease      2008 non-null   int64
 4   connective_tissue_disease                  2008 non-null   int64
 5   peptic_ulcer_disease                       2006 non-null   float64
 6   diabetes                                   2008 non-null   int64
 7   moderate_to_severe_chronic_kidney_disease  2006 non-null   float64
 8   hemiplegia                                 2008 non-null   int64
 9   leukemia                                   2008 non-null   int64
 10  malignant_lymphoma                         2008 non-null   int64
 11  solid_tumor                                2008 non-null   int64
 12  liver_disease                              2007 non-null   float64
 13  aids                                       2008 non-null   int64
 14  cci_score                                  2003 non-null   float64
 15  type_ii_respiratory_failure                2008 non-null   object
 16  acute_renal_failure                        2008 non-null   int64
dtypes: float64(4), int64(12), object(1)
memory usage: 266.8+ KB

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,acute_renal_failure
count,2008.000000,2008.000000,2008.000000,2008.000000,2008.000000,2006.000000,2008.000000,2006.000000,2008.000000,2008.0,2008.000000,2008.000000,2007.000000,2008.000000,2003.000000,2008.000000
mean,797747.542829,0.074701,0.057271,0.116036,0.001992,0.022433,0.232072,0.236291,0.005976,0.0,0.000498,0.019422,0.041854,0.001992,1.861707,0.003486
std,41127.801740,0.262974,0.232417,0.320348,0.044599,0.148123,0.422260,0.424909,0.077093,0.0,0.022316,0.138038,0.200304,0.044599,0.961469,0.058955
min,722128.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,763164.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,798758.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
75%,829399.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
max,905720.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,6.000000,1.000000

In [19]:
# checked number of rows and columns

df.shape

(2008, 17)

In [21]:
# Checked all column names

df.columns.tolist()

['inpatient_number',
 'cerebrovascular_disease',
 'dementia',
 'chronic_obstructive_pulmonary_disease',
 'connective_tissue_disease',
 'peptic_ulcer_disease',
 'diabetes',
 'moderate_to_severe_chronic_kidney_disease',
 'hemiplegia',
 'leukemia',
 'malignant_lymphoma',
 'solid_tumor',
 'liver_disease',
 'aids',
 'cci_score',
 'type_ii_respiratory_failure',
 'acute_renal_failure']

In [6]:
# Checked datatypes and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2008 entries, 0 to 2007
Data columns (total 17 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   inpatient_number                           2008 non-null   int64
 1   cerebrovascular_disease                    2008 non-null   int64
 2   dementia                                   2008 non-null   int64
 3   chronic_obstructive_pulmonary_disease      2008 non-null   int64
 4   connective_tissue_disease                  2008 non-null   int64
 5   peptic_ulcer_disease                       2006 non-null   float64
 6   diabetes                                   2008 non-null   int64
 7   moderate_to_severe_chronic_kidney_disease  2006 non-null   float64
 8   hemiplegia                                 2008 non-null   int64
 9   leukemia                                   2008 non-null   int64
 10  malignant_lymphoma                         2008 non-null   int64
 11  solid_tumor                                2008 non-null   int64
 12  liver_disease                              2007 non-null   float64
 13  aids                                       2008 non-null   int64
 14  cci_score                                  2003 non-null   float64
 15  type_ii_respiratory_failure                2008 non-null   object
 16  acute_renal_failure                        2008 non-null   int64
dtypes: float64(4), int64(12), object(1)
memory usage: 266.8+ KB

In [22]:
# Checked dublicate rows

df.duplicated().sum()

np.int64(0)

In [23]:
# Checked duplicate patient IDs

df["inpatient_number"].duplicated().sum()

np.int64(0)

In [24]:
# Checked number of unique patients: Because this is essentially a patient-level comorbidity table, ideally each inpatient_number should occur once.

df["inpatient_number"].nunique()

2008

In [25]:
# Checked missing values

df.isnull().sum()

inpatient_number                             0
cerebrovascular_disease                      0
dementia                                     0
chronic_obstructive_pulmonary_disease        0
connective_tissue_disease                    0
peptic_ulcer_disease                         2
diabetes                                     0
moderate_to_severe_chronic_kidney_disease    2
hemiplegia                                   0
leukemia                                     0
malignant_lymphoma                           0
solid_tumor                                  0
liver_disease                                1
aids                                         0
cci_score                                    5
type_ii_respiratory_failure                  0
acute_renal_failure                          0
dtype: int64

In [26]:
# Patient records containing missing values

df[df.isnull().any(axis=1)]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
467,782088,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,0
743,791916,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,1
817,794590,0,0,0,0,NaN,1,1.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1003,818307,0,0,0,0,NaN,1,0.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1497,793609,0,0,0,0,0.0,1,1.0,0,0,0,0,NaN,0,NaN,nontypeii,0

In [27]:
# checked how the four affected variables are coded:

columns = [
    'peptic_ulcer_disease',
    'moderate_to_severe_chronic_kidney_disease',
    'liver_disease',
    'cci_score'
]

for col in columns:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 peptic_ulcer_disease
peptic_ulcer_disease
0.0    1961
1.0      45
NaN       2
Name: count, dtype: int64

 moderate_to_severe_chronic_kidney_disease
moderate_to_severe_chronic_kidney_disease
0.0    1532
1.0     474
NaN       2
Name: count, dtype: int64

 liver_disease
liver_disease
0.0    1923
1.0      84
NaN       1
Name: count, dtype: int64

 cci_score
cci_score
1.0    770
2.0    699
3.0    368
4.0     94
0.0     56
5.0     15
NaN      5
6.0      1
Name: count, dtype: int64

NaN means the information is missing, replacing it with 0 would assert that those patients definitely did not have the condition. First inspect those records:

In [28]:
df[df[
    'peptic_ulcer_disease'
].isnull()]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
817,794590,0,0,0,0,NaN,1,1.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1003,818307,0,0,0,0,NaN,1,0.0,0,0,0,0,0.0,0,NaN,nontypeii,0

In [40]:
df[df[
    'moderate_to_severe_chronic_kidney_disease'
].isnull()]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
467,782088,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,0
743,791916,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,1

In [39]:
print(df['liver_disease'].value_counts(dropna=False))

print("\nCCI Score:")
print(df['cci_score'].value_counts(dropna=False).sort_index())

liver_disease
0.0    1923
1.0      84
NaN       1
Name: count, dtype: int64

CCI Score:
cci_score
0.0     56
1.0    770
2.0    699
3.0    368
4.0     94
5.0     15
6.0      1
NaN      5
Name: count, dtype: int64

In [41]:
# check whether the same patients have missing values in multiple column

df[df.isnull().any(axis=1)]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
467,782088,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,0
743,791916,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,1
817,794590,0,0,0,0,NaN,1,1.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1003,818307,0,0,0,0,NaN,1,0.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1497,793609,0,0,0,0,0.0,1,1.0,0,0,0,0,NaN,0,NaN,nontypeii,0

In [55]:
# Find all rows containing at least one missing value
missing_rows = df[df.isnull().any(axis=1)]

In [56]:
# cleaner table showing exactly which missing values belong to which patients

missing_rows[[
    'inpatient_number',
    'peptic_ulcer_disease',
    'moderate_to_severe_chronic_kidney_disease',
    'liver_disease',
    'cci_score'
]]

,inpatient_number,peptic_ulcer_disease,moderate_to_severe_chronic_kidney_disease,liver_disease,cci_score
467,782088,0,<NA>,0,NaN
743,791916,0,<NA>,0,NaN
817,794590,<NA>,1,0,NaN
1003,818307,<NA>,0,0,NaN
1497,793609,0,1,<NA>,NaN

The dataset contained 10 missing values across 5 patient records. Missing values were found in peptic ulcer disease, moderate-to-severe chronic kidney disease, liver disease, and CCI score. Because the missingness was very small and replacing missing clinical information with 0 could incorrectly indicate absence of disease, the missing values were retained as NaN. Records may be excluded only from analyses requiring the affected variables.

In [43]:
# Check unique values - Most of these columns represent whether the patient has a particular condition.
# We want to determine how the dataset represents disease status—for example, 0/1, Yes/No, or some other coding.

for col in df.columns:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 inpatient_number
inpatient_number
857781    1
764959    1
746519    1
756843    1
744531    1
         ..
811560    1
797417    1
797416    1
870126    1
791864    1
Name: count, Length: 2008, dtype: int64

 cerebrovascular_disease
cerebrovascular_disease
0    1858
1     150
Name: count, dtype: int64

 dementia
dementia
0    1893
1     115
Name: count, dtype: int64

 chronic_obstructive_pulmonary_disease
chronic_obstructive_pulmonary_disease
0    1775
1     233
Name: count, dtype: int64

 connective_tissue_disease
connective_tissue_disease
0    2004
1       4
Name: count, dtype: int64

 peptic_ulcer_disease
peptic_ulcer_disease
0.0    1961
1.0      45
NaN       2
Name: count, dtype: int64

 diabetes
diabetes
0    1542
1     466
Name: count, dtype: int64

 moderate_to_severe_chronic_kidney_disease
moderate_to_severe_chronic_kidney_disease
0.0    1532
1.0     474
NaN       2
Name: count, dtype: int64

 hemiplegia
hemiplegia
0    1996
1      12
Name: count, dtype: int64

 leukemia
leukemia
0    2008
Name: count, dtype: int64

 malignant_lymphoma
malignant_lymphoma
0    2007
1       1
Name: count, dtype: int64

 solid_tumor
solid_tumor
0    1969
1      39
Name: count, dtype: int64

 liver_disease
liver_disease
0.0    1923
1.0      84
NaN       1
Name: count, dtype: int64

 aids
aids
0    2004
1       4
Name: count, dtype: int64

 cci_score
cci_score
1.0    770
2.0    699
3.0    368
4.0     94
0.0     56
5.0     15
NaN      5
6.0      1
Name: count, dtype: int64

 type_ii_respiratory_failure
type_ii_respiratory_failure
nontypeii    1894
typeii        114
Name: count, dtype: int64

 acute_renal_failure
acute_renal_failure
0    2001
1       7
Name: count, dtype: int64

In [45]:
# Check CCI score. 
# cci_score is different from the binary disease columns because it represents the Charlson Comorbidity Index score.

df["cci_score"].describe()

count    2003.000000
mean        1.861707
std         0.961469
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         6.000000
Name: cci_score, dtype: float64

In [46]:
df["cci_score"].value_counts(dropna=False).sort_index()

cci_score
0.0     56
1.0    770
2.0    699
3.0    368
4.0     94
5.0     15
6.0      1
NaN      5
Name: count, dtype: int64

In [47]:
# Check data types

df.dtypes

inpatient_number                               int64
cerebrovascular_disease                        int64
dementia                                       int64
chronic_obstructive_pulmonary_disease          int64
connective_tissue_disease                      int64
peptic_ulcer_disease                         float64
diabetes                                       int64
moderate_to_severe_chronic_kidney_disease    float64
hemiplegia                                     int64
leukemia                                       int64
malignant_lymphoma                             int64
solid_tumor                                    int64
liver_disease                                float64
aids                                           int64
cci_score                                    float64
type_ii_respiratory_failure                   object
acute_renal_failure                            int64
dtype: object

Convert nullable integer Int64 rather than ordinary int64.The capital I in Int64 is important. Pandas Int64 allows:
0
1
<Na>
In peptic_ulcer_disease ,moderate_to_severe_chronic_kidney_disease ,liver_disease

In [48]:
binary_cols_with_missing = [
    'peptic_ulcer_disease',
    'moderate_to_severe_chronic_kidney_disease',
    'liver_disease'
]

df[binary_cols_with_missing] = (
    df[binary_cols_with_missing].astype('Int64')
)

In [50]:
df[binary_cols_with_missing].dtypes

peptic_ulcer_disease                         Int64
moderate_to_severe_chronic_kidney_disease    Int64
liver_disease                                Int64
dtype: object

In [51]:
# Check numeric range

df.describe().T

,count,mean,std,min,25%,50%,75%,max
inpatient_number,2008.0,797747.542829,41127.80174,722128.0,763164.5,798758.0,829399.75,905720.0
cerebrovascular_disease,2008.0,0.074701,0.262974,0.0,0.0,0.0,0.0,1.0
dementia,2008.0,0.057271,0.232417,0.0,0.0,0.0,0.0,1.0
chronic_obstructive_pulmonary_disease,2008.0,0.116036,0.320348,0.0,0.0,0.0,0.0,1.0
connective_tissue_disease,2008.0,0.001992,0.044599,0.0,0.0,0.0,0.0,1.0
peptic_ulcer_disease,2006.0,0.022433,0.148123,0.0,0.0,0.0,0.0,1.0
diabetes,2008.0,0.232072,0.42226,0.0,0.0,0.0,0.0,1.0
moderate_to_severe_chronic_kidney_disease,2006.0,0.236291,0.424909,0.0,0.0,0.0,0.0,1.0
hemiplegia,2008.0,0.005976,0.077093,0.0,0.0,0.0,0.0,1.0
leukemia,2008.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
malignant_lymphoma,2008.0,0.000498,0.022316,0.0,0.0,0.0,0.0,1.0
solid_tumor,2008.0,0.019422,0.138038,0.0,0.0,0.0,0.0,1.0
liver_disease,2007.0,0.041854,0.200304,0.0,0.0,0.0,0.0,1.0
aids,2008.0,0.001992,0.044599,0.0,0.0,0.0,0.0,1.0
cci_score,2003.0,1.861707,0.961469,0.0,1.0,2.0,2.0,6.0
acute_renal_failure,2008.0,0.003486,0.058955,0.0,0.0,0.0,0.0,1.0

Most comorbidity variables are binary indicators coded as:
- **0 = Condition absent**
- **1 = Condition present**
The minimum and maximum values of the disease variables were checked to confirm that they fall within the expected range of 0 to 1. No unexpected values were observed in the binary variables shown.Some variables have fewer than 2,008 observations because they contain missing values. These include peptic ulcer disease, moderate-to-severe chronic kidney disease, and liver disease, which is consistent with the previous missing-value assessment.The mean of a binary variable represents the proportion of records coded as 1. For example, a mean of approximately 0.23 for diabetes indicates
that about 23% of the patients are coded as having diabetes.Overall, the numeric range assessment indicates that the binary comorbidity variables are coded within their expected 0–1 range.

In [52]:
# Reset the Index

df = df.reset_index(drop=True)

In [57]:
# Save the cleaned dataset and supporting reports

# Create the output folder if it does not exist
output_folder.mkdir(exist_ok=True)

# Save the cleaned dataset
df.to_csv(
    output_folder/"Team7_CodeAvengers_Category1_DataCleaning_patienthistory_cleaned.csv",
    index=False
)



# Display the saved files and their locations
print("All files saved successfully!\n")

for file in output_folder.iterdir():
    if file.is_file():
        print("Saved:", file.name)

print("\nOutput Folder:", output_folder)
print("Final Cleaned Dataset Shape:", df.shape)

All files saved successfully!

Saved: patienthistory_cleaned.csv
Saved: Team7_CodeAvengers_Category1_DataCleaning_patienthistory_cleaned.csv

Output Folder: C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026\cleaned_data
Final Cleaned Dataset Shape: (2008, 17)

In [58]:
# Write to csv

df.to_csv(
    r"C:\Users\haris\OneDrive\Desktop\SUGANYA\DA215\Python\Python_Hackathon_Sep_2026\cardiac_failure\Team7_CodeAvengers_Category1_DataCleaning_patienthistory_cleaned.csv",
    index=False
)